chainer/chainermn

- docs/source/tutorial/step2_datasets_evaluators.rst
- examples/mnist/train_mnist.py
When mnist example is run with -b 128, epoch 2 log is not output.
Its example is :
```
$ mpiexec -n 4 python examples/mnist/train_mnist.py -b 128 -g 
GPU: 0
epoch       main/loss   validation/main/loss  main/accuracy  validation/main/accuracy  elapsed_time
1           0.314679    0.126357              0.911149       0.96061                   3.49345       
2           0.0935955                         0.97269                                  4.91697       
3           0.0541213   0.0860978             0.985577       0.973357                  6.36811       
4           0.034525    0.0751695             0.989183       0.976068                  7.84156       
5           0.0278316   0.0692897             0.992455       0.977947                  9.31424       
6           0.0196535 …
```
> fix bug of LogReport in mnist example

- chainermn/communicators/_base.py
- tests/test_communicator.py
This PR fixes the issue that `FlatCommunicator` fails when `allreduce_grad` is called more than once.
> Fix assert for cases when use_nccl == False

- examples/mnist/train_mnist.py
For testing & debugging purpose, it would be useful to add `--communicator` option to `train_mnist.py` file.
> Add communicator option to MNIST exmaple

- examples/mnist/train_mnist.py
Log messages from the MNIST examples were not very clear, especially when a user is facing a trouble.
This PR updates the log message to be more friendly and helpful.
- The message is now printed only once (communicator message was printed by each process)
- Number of processes is printed (for troubleshooting)
- Formatted more prettier
```
==========================================
Num process (COMM_WORLD): 2
Using GPUs
Using hierarchical communicator
Num unit: 1000
Num Minibatch-size: 100
Num epoch: 5
==========================================
```
> Improve message mnist example

- docs/source/tutorial/step1_communicators_optimizers.rst
> Mention --gpu option in the MNIST tutorial 

- chainermn/functions/point_to_point_communication.py
- chainermn/link.py
- tests/test_link.py
In #98 , `MultiNodeChainList` does not allow to send / recv to the same process (see https://github.com/chainer/chainermn/blob/master/chainermn/link.py#L129).
This pull request extends `MultiNodeChainList` a little bit to allow it.
See examples in `test_link.py`:
```python 
class BranchParent2(chainermn.MultiNodeChainList):
def __init__(self, size, comm, rank_children):
super(BranchParent2, self).__init__(comm=comm)
ranks = [comm.rank] + rank_children
self.add_link(BranchSubA(size), rank_in=None, rank_out=ranks)
self.add_link(BranchSubA(size), rank_in=comm.rank, rank_out=comm.rank)
self.add_link(BranchSubB(size), rank_in=ranks, rank_out=None)
class BranchParent3(chainermn.MultiNodeChainList):
def __init__(self, size, comm, rank_children):
super(BranchParent3, self).__init__(comm=comm) …
```
> MultiNodeChainList with self branching

- chainermn/link.py
> Add None to the type specification

- examples/imagenet/models_v2/alex.py
- examples/imagenet/models_v2/googlenet.py
- examples/imagenet/models_v2/googlenetbn.py
- examples/imagenet/models_v2/nin.py
- examples/imagenet/models_v2/resnet50.py
Actually models other than NIN work correctly with the current code, but NIN model raises the error below with Chainer v2.
```
$ cd chainermn/examples/imagenet/models_v2
$ python -c 'from nin import NIN; model = NIN()'
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/Users/shunta/Codes/chainermn/examples/imagenet/models_v2/nin.py", line 18, in __init__
None, (96, 96, 96), 11, stride=4, wscale=w),
File "/Users/shunta/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/chainer/links/connection/mlp_convolution_2d.py", line 69, in __init__
argument.check_unexpected_kwargs(kwargs, wscale=msg)
File "/Users/shunta/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/chainer/utils/argument.py", line 4, in check_unexpected_kwargs
raise …
```
> Fix imagenet models for v2

- chainermn/functions/batch_normalization.py
- chainermn/links/__init__.py
- chainermn/links/batch_normalization.py
- docs/source/reference/index.rst
- tests/links_tests/test_batch_normalization.py
This PR adds a new link `MultiNodeBatchNormalization`. When using `chainer.link.BatchNormalization`, batch mean and std are computed independently for the local batch in each worker. In contrast, when using this `MultiNodeBatchNormalization`, workers communicate to conduct 'correct' batch normalization (e.g., obtaining mean and std for the whole global batch).
> Add MultiNodeBatchNormalization

- .travis.yml
Currently, CI on Travis CI often fails because of deadlocks in 3-process test_mnist.
Although I don't find the exact reason of the deadlock, tests with up to 2 processes
does not suffer from the deadlock issue.
This PR changes the number of processes in the MPI tests (1,2,3) to two processes in `.travis.yml`.
Also, this PR changes to invoke `nosetests` command for each `test_*.py` files so it can avoid deadlocks.
> Reduce the number of procs of MPI test for robust CI

- chainermn/datasets/scatter_dataset.py
- examples/seq2seq/seq2seq.py
- tests/test_dataset.py
In mpi4py objects sent with Comm.send() are always pickled every time;
Thus, whole dataset is pickled at sending to each of all rank > 0
nodes, as self._dataset is included in all SubDataset [1]. Thus in
scatter_dataset function has been inefficient that took >30 seconds
when distributing ImageNet 2012 dataset, even if it was just for file
names and tags, for example, which is optimized to finish in <5
seconds in our experimental environment.
This patch changes the repeat of Comm.send() to a combination of
Comm.bcast() of whole dataset and Comm.send() of range of each
scattered dataset. With this change number of picking whole dataset
has been reduced from N to 1, where N denotes number of MPI processes.
But this fix as a drawback in error handling, especially in case
OverflowError is …
> Avoid sending SubDataset and use broadcast for datasets

- chainermn/communicators/_base.py
- chainermn/functions/point_to_point_communication.py
- chainermn/links/multi_node_chain_list.py
- tests/functions_tests/test_point_to_point_communication.py
- tests/test_communicator.py
- tests/test_link.py
The current version of `chainermn.functions.{send,recv}` can communicate with only one array.
This hinders the flexibility of `MultiNodeChainList` since we can't send multiple arrays at the same time:
```python
class NN0(chainer.Chain):
def __call__(self, x):
y0 = some_calculation_nn0_0(x)
y1 = some_calculation_nn1_1(x)
return y0, y1
class NN1(chainer.Chain):
def __call__(self, y):
y0, y1 = y
return some_calculation_nn1(y0, y1)
class Model_on_Process_0(chainermn.MultiNodeChainList):
def __init__(self, comm):
super(Model_on_Process_0, self).__init__(comm=comm)
self.add_link(NN0(), rank_in=None, rank_out=1)
class Model_on_Process_1(chainermn.MultiNodeChainList):
def __init__(self, comm):
super(Model_on_Process_1, self).__init__(comm=comm)
self.add_link(NN1(), rank_in=0, rank_out=None)
```
> Support tuple data communication

- chainermn/__init__.py
- chainermn/extensions/__init__.py
- chainermn/extensions/checkpoint.py
- examples/imagenet/train_imagenet.py
- examples/mnist/train_mnist_cpr.py
- tests/test_checkpoint.py
- tests/test_mnist.py
At each distributed checkpointing, all processes run MPI gather and
MPI bcast to share common set of iteration numbers that has
corresponding snapshot. Also at startup it runs syncing among
procceses, if _DistCPRExtension.maybe_resume() is explicitly called.
Limitations
* Number of nodes must be the same among runs
* In resuming all processes must reachable to its own snapshot files
that has corresponding rank numbers
* Needs manual operation when any latest set of files are broken;
just remove them and use one more older set
> Add simple and distributed checkpointing and automatic recovery

- chainermn/communicators/_base.py
- chainermn/functions/__init__.py
- chainermn/functions/collective_communication.py
- docs/source/reference/index.rst
- tests/functions_tests/test_collective_communication.py
This P/R adds an advanced model-parallel interface `chainermn.functions.all_to_all`, which enables forward/backward all-to-all computation.
Unlike `chainermn.functions.recv`, this interface does not need `delegate_variable` since it has input variables.
If you would like to define a complicated model which has multiple independent computational components on one process, you can link the former component to the inputs of `all_to_all` by `chainermn.functions.pseudo_connect`.
> Support all-to-all

- .travis.yml
In the current `.travis.yml` script, the unit tests produce warnings such as 
```
/home/kfukuda/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/chainer/utils/experimental.py:104: FutureWarning: chainermn.communicators.CommunicatorBase.all_to_all is experimental. The interface can change in the future.
FutureWarning)
```
This is annoying and makes reading the CI log harder. 
This PR adds a line to specify `PYTHONWARNINGS` environmental variable to supress `FutureWarning` warnings from Python interpreter.
> Added PYTHONWARNING env var to .tavis.yml

- chainermn/communicators/pure_nccl_communicator.py
The original code has a minor bug regarding to array lengths of GPU buffers in `PureNcclCommunicator`.
* `n_elems_total` is less than or equal to `n_elems_per_node`
* `ret` has length `n_elems_total `
* `gpu_buffer_b` tries to copy `nbytes_buffer` (= 4 * `n_bytes_per_node `) from `ret`, which may be longer than the length of `ret` and causes error.
> Fix array length bug of PureNcclCommunicator

- chainermn/functions/batch_normalization.py
I removed a variable that causes ChainerMN to crash when used with the latest CuPy version. `chainer.cuda.cudnn.cudnn` has been renamed `chainer.cuda.cudnn.py_cudnn`, but since it was not used in the code, I simply removed it.
> Remove outdated cudnn variable to make compatible with CuPy v4

- chainermn/optimizers.py
- tests/optimizer_tests/test_multi_node_optimizer.py
When a new layer is added to a model dynamically, its parameters needs to be sent all nodes.
But, the current MultiNodeOptimizer only sends model parameters first once.
Therefore, I fixed MultinodeOptimizer to send parameters all nodes when a model is changed.
> Fix update bug in MultiNodeOptimizer

- chainermn/communicators/__init__.py
* Remove the experimental flag of `pure_nccl` communicator #164
* Move the `pure_nccl` communicator to the top of the table to recommend it as our first choice
> Update the communicators table

- chainermn/extensions/multi_node_evaluator.py
With Chainer #3952 current proxy implementation cannot handle
class attributes of Chainer's latest Evaluator.name, thus move
to just wrap the evaluate() method with multi-node support.
With this and #149 merged, ChainerMN will work with Chainer 4.0.
Note: consequence of this issue is, validation evaluator cannot have it's name `validation` and key `validation/main/loss` and `validation/main/accuracy` does not exist; which has two unexpected effects:
1. instead the evaluator overwrites `main/loss` and `main/accuracy`, printing no result in LogReport
2. due to the unexpected lack of `validation/main/loss` or accuracy user codes may fail (and following functionality such as saving actual models, might fail)
> Change MultiNodeEvaluator to object patching from proxy pattern

- .travis.yml
- docs/source/installation/guide.rst
- setup.py
- tests/functions_tests/test_collective_communication.py
- tests/functions_tests/test_point_to_point_communication.py
- tests/links_tests/test_batch_normalization.py
- tests/test_communicator.py
- tests/test_dataset.py
- tests/test_link.py
- tests/test_mnist.py
- tests/test_node_aware_communicator_base.py
- Chainer has moved to pytest since 3.0.0 and now MN follows.  An
example of testing tool mismatch is: Chainer's parameterized test
started checking all Exceptions including nose SkipTest(), at #3963
and #3876 which are included in 3.2.0 and 4.0, and all unit tests
that skips is recognized as test failure. Additionally, this patch
starts supporting Chainer 3.2.0 and 2.1.0, dropping 1.x as well (One
more issue to support 4.0 remains).
- Remove `nccl` selector on running unit tests and all merged to
`gpu`, as ChainerMN requires NCCL by default.
- Also, mixture of chainer.testing.attr.gpu and
chainer.testing.parameterize, with passing pytest to `-m 'not gpu'`
does not work in pytest because nose's attributes are direct
attribute to test object or function, in contrast to pytest. Thus
this …
> Move from nose to pytest

- chainermn/communicators/_base.py
- chainermn/communicators/_communication_utility.py
- chainermn/communicators/dummy_communicator.py
- chainermn/communicators/flat_communicator.py
- chainermn/communicators/hierarchical_communicator.py
- chainermn/communicators/non_cuda_aware_communicator.py
- chainermn/communicators/pure_nccl_communicator.py
- chainermn/communicators/single_node_communicator.py
- chainermn/communicators/two_dimensional_communicator.py
- tests/chainermn_tests/communicator_tests/test_communicator.py
- tests/chainermn_tests/communicator_tests/test_node_aware_communicator_base.py
In the current communicator class hierarchy, not all communicator have `intra_rank` attribute due to a historical reason.
The attribute is currently used to determine if ChainerMN is using GPUs because `intra_rank` was implemented to determine GPUs to use in a local physical node. However, GPU ID and `intra_rank` are different concepts and the usage is inappropriate.
This PR merges`NodeAwareCommunicator` into `CommunicatorBase` so `CommunicatorBase` class and all of its ancestors have `intra_rank` attribute.
> Add intra_rank to all communicators

- README.md
- chainermn_bibtex.txt
I add the reference of ChainerMN paper which was accepted in the workshop ML Systems at NIP S2017.
> Add reference of ChainerMN paper

- tests/chainermn_tests/datasets_tests/test_mnist.py
- tests/chainermn_tests/functions_tests/test_collective_communication.py
- tests/chainermn_tests/functions_tests/test_point_to_point_communication.py
Some tests lack `import chainer.testing`, so the produce the following error when invoked alone by `pytest`.
```
./tests/chainermn_tests/functions_tests/test_point_to_point_communication.py
============================= test session starts ==============================
platform linux -- Python 3.6.0, pytest-3.0.5, py-1.4.32, pluggy-0.4.0 -- /home/kfukuda/.pyenv/versions/anaconda3-4.3.1/bin/python
cachedir: .cache
rootdir: /home/kfukuda/chainermn, inifile:
collecting ... collected 0 items / 1 errors
==================================== ERRORS ====================================
ERROR collecting tests/chainermn_tests/functions_tests/test_point_to_point_communication.py
tests/chainermn_tests/functions_tests/test_point_to_point_communication.py:170: in <module>
@chainer.testing.attr.gpu
E …
```
> Fix importing errors in unit tests 

- .travis.yml
Chainer 3.3 has been released.
This PR adds Chainer 3.3 to the Travis CI test matrix.
To keep CI time short, it drops Chainer 3.1 tests.
> Adds test for Chainer 3.3

- chainermn/communicators/pure_nccl_communicator.py
- chainermn/optimizers.py
- tests/chainermn_tests/optimizer_tests/test_double_buffering_optimizer.py
I fixed bugs in DoubleBufferingOptimizer and PureNcclCommunicator.
Current double buffering feature has two bugs.
1. runs actual_optimizer.update() when it is not required. This bug occurs when model is changed dynamically.
2. doesn't wait for GPU process on default stream after pack_params.
I fixed them.
> Fix bugs in DoubleBufferingOptimizer and PureNcclCommunicator

- chainermn/links/n_step_rnn.py
This PR replaces #205.
In Chainer >4.0.0b3, internal structures of `n_step_rnn` has been drastically changed.
Thus we cannot retrieve the number of internal cells of RNN in a simple way.
I created PR chainer/chainer#4417, considering maintenancability to keep backward compatibility, to add `n_cells` property to `n_step_rnn` family.
This PR simply uses them to rewrite `MultiNodeNStepRNN`, based on #205.
> Fix MultiNodeNStepRNN to use Chainer n_cells

- chainermn/communicators/_memory_utility.py
- tests/chainermn_tests/communicator_tests/test_communicator.py
If an input array is not C-contiguous nor Fortran-contiguous, `MPI_Ssend` will fail.
> Check contiguousness of outgoing arrays

- chainermn/communicators/_memory_utility.py
- chainermn/communicators/pure_nccl_communicator.py
- chainermn/optimizers.py
I optimized `PureNcclCommunicator` to accelerate training with double buffering.
> Optimize PureNcclCommunicator to accelerate training with double buffering 

- chainermn/links/n_step_rnn.py
I fixed a bug of NStepRNN. 
An error occurs in current  MultiNodeNStepRNN when Chainer v4.0.0b1-v4.0.0b4.
After an offline discussion, ChainerMN will not support Chainer v4.0.0b1-v4.0.0b4, because they are beta version.
So, I changed to raise the exception in MultiNodeNStepRNN  when Chainer v4.0.0b1-v4.0.0b4 were used.
> Fix a bug of NStepRNN

- chainermn/communicators/_base.py
- chainermn/communicators/_communication_utility.py
- chainermn/communicators/dummy_communicator.py
- chainermn/communicators/flat_communicator.py
- chainermn/communicators/hierarchical_communicator.py
- chainermn/communicators/mpi_communicator_base.py
- chainermn/communicators/naive_communicator.py
- chainermn/communicators/non_cuda_aware_communicator.py
- chainermn/communicators/pure_nccl_communicator.py
- chainermn/communicators/single_node_communicator.py
- chainermn/communicators/two_dimensional_communicator.py
- chainermn/datasets/scatter_dataset.py
- chainermn/extensions/allreduce_persistent.py
- chainermn/extensions/checkpoint.py
- chainermn/extensions/multi_node_evaluator.py
- chainermn/functions/batch_normalization.py
- chainermn/iterators/multi_node_iterator.py
- chainermn/optimizers.py
- examples/dcgan/train_dcgan.py
- examples/imagenet/train_imagenet.py
- examples/mnist/train_mnist.py
- examples/mnist/train_mnist_checkpoint.py
- examples/seq2seq/seq2seq.py
- examples/seq2seq/seq2seq_mp1.py
- tests/chainermn_tests/communicator_tests/test_communication_utility.py
- tests/chainermn_tests/communicator_tests/test_communicator.py
- tests/chainermn_tests/communicator_tests/test_node_aware_communicator_base.py
- tests/chainermn_tests/datasets_tests/test_dataset.py
This patch introduces naming rule to communicator API methods, as
adding suffix `_obj` for Python object transfers. Also changes
`broadcast_data` to `bcast_data` to unify broadcasting names to bcast,
which had possibility to confuse users with `broadcast_to` in
chainer.functions. Also it hides mpi_comm usage (except `Barrier()`
usage). This patch also introduce MpiCommunicatorBase to make
CommunicatorBase purely "virtual" interface class that has no
implementation, but just interface.
> Clean up Communicator interface with changes

- .travis.yml
- docs/source/installation/guide.rst
- setup.py
Chainer and CuPy 4.0.0 have been released today.
> Update supported Chainer versions

- chainermn/functions/point_to_point_communication.py
- tests/chainermn_tests/functions_tests/test_point_to_point_communication.py
The current version of `chainermn.functions.send` will cause deadlock since its `backward` cannot be called in the case where `require_grad` of all inputs for `send` are not set.
I solved simply by adding a dummy variable to inputs of `send`.
(This PR depends on #213)
> Fix send to avoid deadlock without inputs does not reqires grad

- chainermn/iterators/multi_node_iterator.py
- tests/chainermn_tests/iterators_tests/test_multi_node_iterator.py
The old `MultiNodeIterator` fails to handle paired datasets, i.e.,
```
[(x1, y1), (x2, y2), ... , (xN, yN)]
```
In this implementation, first the master process confirms whether the dataset is paired or not, and broadcast twice (for the sequence `[x1, x2, ... , xN]` and `[y1, y2, ... , yN]`) in paired case.
> Fix MultiNodeIterator for paired datasets

- tests/chainermn_tests/iterators_tests/test_iterator_compatibility.py
- tests/chainermn_tests/iterators_tests/test_multi_node_iterator.py
- tests/conftest.py
Our internal tests failed at current master. Most test failure are like this:
```
chainermn_tests/iterators_tests/test_multi_node_iterator.py::TestMultiNodeIterator_param_0::test_mn_iterator 
chainermn_tests/iterators_tests/test_multi_node_iterator.py::TestMultiNodeIterator_param_1::test_mn_iterator [f58ef00bba8e:00234] *** Process received signal ***
[f58ef00bba8e:00234] Signal: Segmentation fault (11)
[f58ef00bba8e:00234] Signal code: Address not mapped (1)
[f58ef00bba8e:00234] Failing at address: 0x2d45488
```
Its cause was that we did not use forkserver when using MultiProcessIterator.When using multiprocess and InfiniBand, segmentation fault sometimes occurs if forkserver is not used.
To solve this problem, I use forkserver.
> Fix tests of MultiNodeIterator

- chainermn/communicators/communicator_base.py
- chainermn/communicators/mpi_communicator_base.py
- tests/chainermn_tests/communicator_tests/test_communicator.py
This is based on #235 and addresses #234 .
>  Add allreduce method to communicator interface with implementation

- chainermn/communicators/_communication_utility.py
- chainermn/communicators/dummy_communicator.py
- chainermn/communicators/flat_communicator.py
- chainermn/communicators/hierarchical_communicator.py
- chainermn/communicators/mpi_communicator_base.py
- chainermn/communicators/non_cuda_aware_communicator.py
- chainermn/communicators/pure_nccl_communicator.py
- chainermn/communicators/single_node_communicator.py
- chainermn/communicators/two_dimensional_communicator.py
- tests/chainermn_tests/communicator_tests/test_communicator.py
- tests/chainermn_tests/communicator_tests/test_node_aware_communicator_base.py
- tests/chainermn_tests/optimizer_tests/test_double_buffering_optimizer.py
- tests/chainermn_tests/optimizer_tests/test_multi_node_optimizer.py
This PR refactors initialization of communicator to remove unused mpi comm or nccl comm.
It solves https://github.com/chainer/chainermn/issues/224
> Remove unused nccl comm and mpi comm

- chainermn/communicators/_memory_utility.py
- chainermn/communicators/communicator_base.py
- chainermn/communicators/mpi_communicator_base.py
- chainermn/functions/collective_communication.py
- chainermn/functions/point_to_point_communication.py
- chainermn/links/multi_node_chain_list.py
- chainermn/links/n_step_rnn.py
- tests/chainermn_tests/functions_tests/test_collective_communication.py
- tests/chainermn_tests/functions_tests/test_point_to_point_communication.py
The current communicator always returns `numpy` arrays when it received data (e.g. `recv`, `bcast`, etc.).
This is sometimes problematic in terms of communication speed, because p2p/collective communication always invoked by D2H/H2D memcpy, even though GPU-to-GPU communication is intended.
Received data should be allocated on GPU in case where the sender sends cupy arrays.
Modified `alltoall`, `recv`, `bcast`, `gather`, `allgather`, `allreduce`, `scatter` to
- allocate received data on GPU if needed (cf. `_memory_utility.get_device_memory_pointer`)
- remove device specifier and CUDA cast codes from the corresponding `chainermn.functions`
> Modify receivers in communicator to use cupy array

- chainermn/communicators/_memory_utility.py
- chainermn/communicators/mpi_communicator_base.py
- chainermn/iterators/multi_node_iterator.py
- tests/chainermn_tests/communicator_tests/test_communicator.py
(rebased version of #265 )
Add `dtype` in `_MessageType` (see `mpi_communicator_base.py`) to
handle other dtype than `numpy.float32`.  Main change is to determine
MPI type based on `_MessageType` when calling MPI APIs, e.g.,
```python
self.mpi_comm.Gatherv(
sbuf,
[_memory_utility.get_device_memory_pointer(rbuf),
(rlens, _cnt_to_dsp(rlens)), _get_mpi_type(msgtype)],
root)
```
where `_get_mpi_type` converts `_MessageType` to MPI data type.
`MultiNodeIterator` is one of important use cases: Since
`MultiNodeIterator` broadcasts minibatches (consider `{(x: float32, y:
int32)}`-type dataset) every epoch, it needs to broadcast int32 array.
> Enable MultiNodeIterator/MpiCommunicatorBase to handle general data type

- .travis.yml
- chainermn/communicators/_memory_utility.py
- chainermn/communicators/mpi_communicator_base.py
- setup.py
- tests/chainermn_tests/functions_tests/test_collective_communication.py
As results of benchmarks, `cffi` occupies a certain amount of the computation time in model-parallel architecture.
In order to fetch device memories, the current implementation is like
```python
ffi = cffi.FFI()
return ffi.buffer(ffi.cast('void *', array.data.ptr), array.nbytes)
```
but this can be improved as
```python
return ctypes.cast(
array.data.ptr,
ctypes.POINTER(ctypes.c_ubyte, array.nbytes)
).contents
```
> Improve performance of fetching device memory

- .md5sum.txt
- .travis.yml
- .travis_build_mpi.sh
This PR makes several updates to `.travis.yml` 
* Replaced Open MPI 1.6.3 with 2.1.3
* Drop MPICH 3.0.4 so the number of  test cases is reduced (we basically recommend Open MPI)
* Updated Chainer from 4.0.0 to 4.3.1
* Added MD5 checksum check, because an error occurs in downloading a tar file occasionally and thus the test job is marked failed. To avoid this, the script tries to retry the download.
> Travis update

- .travis.yml
Travis CI fails with newly-deployed Python 3.6.5. 
This is because `numpy.dot` takes too long time. 
This PR fixes the issue by adding `OMP_NUM_THREADS=1` to the CI environment.
> added OMP_NUM_THREADS=1
