- examples/mnist/train_mnist.py
This reverts commit 310c6f24fc349510bd1979d2349b684951f3bf1a.
> Revert "Minor update on a message of MNIST example"

- docs/source/installation/guide.rst
> Mention sudo's env-var issue in the installation document

- README.md
> fix link for doc

- .gitignore
Ignore .idea folder, which is automatically created by PyCharm for internal configuration.
> Ignore idea

- chainermn/communicators/_base.py
- chainermn/communicators/hierarchical_communicator.py
- chainermn/dataset.py
This PR replaces lines like `TODO: write comment` to actual comments.
> Adding comments 

- chainermn/functions/point_to_point_communication.py
- chainermn/functions/pseudo_connect.py
- chainermn/link.py
Added names for functions and variables to support debug.
An example image of a computational graph is as follows:
> Clear names for functions and variables

- tests/test_mnist.py
This PR adds MNIST test on GPU.
> Add MNIST test on GPU

- docs/source/reference/index.rst
Just reorder and rename some of the sections.
> Refactor API reference

- .travis.yml
- docs/source/installation/guide.rst
This PR adds CI on Chainer v3.
> Add Chainer v3 Test to Travis CI

- chainermn/__init__.py
- chainermn/extensions/__init__.py
- chainermn/extensions/checkpoint.py
- examples/imagenet/train_imagenet.py
- examples/mnist/train_mnist_checkpoint.py
- tests/test_checkpoint.py
- tests/test_mnist.py
> Rename CPR to checkpointer and mark experimental

- chainermn/functions/collective_communication.py
> Fix Alltoall -> AllToAll

- chainermn/links/n_step_rnn.py
> Add experimental flag to create_multi_node_n_step_rnn

- tests/chainermn_tests/links_tests/test_multi_node_chain_list.py
Current master does not pass unit tests with more than 3 nodes. This is because test_multi_node_chain_list.py:check_tuple_data_model  expects just two processes.
> Pass unit tests more than 3 processes

- chainermn/extensions/multi_node_evaluator.py
- Chainer 3.2.0 support is the priority
- After 1.1 release it will be merged to master again (for Chainer 4.0.0bN users)
- After https://github.com/chainer/chainer/pull/4137 get released #160 will be released as patch update version
> Backport #160

- chainermn/extensions/multi_node_evaluator.py
With Chainer #3952 current proxy implementation cannot handle
class attributes of Chainer's latest Evaluator.name, thus move
to just wrap the evaluate() method with multi-node support.
This reverts commit 75cdd7354876c19354aa348592fd76af69ede95e.
This is reopen of #160 - after https://github.com/chainer/chainer/pull/4145 merged to Chainer 4.0 branch (currently master), and backported to 3.x branch, this will be merged.
> Change MultiNodeEvaluator to object patching from proxy pattern

- docs/source/tutorial/step1_communicators_optimizers.rst
- docs/source/tutorial/step2_datasets_evaluators.rst
This PR fixes #192 : Typos in documentation.
> Fixed typos

- .travis.yml
- chainermn/links/n_step_rnn.py
- docs/source/installation/guide.rst
This PR replaces #220 and #222 (with further version update).
The two pull requests have a circular dependency and must be fixed together.
> Update chainer version 4.0.0rc1 / 3.5

- chainermn/iterators/multi_node_iterator.py
- tests/chainermn_tests/iterators_tests/test_iterator_compatibility.py
- tests/chainermn_tests/iterators_tests/test_multi_node_iterator.py
The current version of ``MutliNodeIterator`` actually works with ``chainer.iterators.MultiprocessIterator``.
> Test the combination of MutliNodeIterator and MultiprocessIterator

- tests/chainermn_tests/functions_tests/test_point_to_point_communication.py
`self.rank_next` ->  `self.rank_send` cf: #214
> Fix p2p-communication test

- docs/source/tutorial/tips_faqs.rst
- examples/mnist/train_mnist.py
This PR adds an entry to the FAQ section about MPI process hang issue.
> Added an FAQ entry about MPI hang issue.

- docs/source/tutorial/tips_faqs.rst
> Update the description about using FP16

- chainermn/communicators/communicator_base.py
- chainermn/communicators/mpi_communicator_base.py
- docs/source/reference/index.rst
> Expose intra- and inter- rank and size

- chainermn/extensions/checkpoint.py
- docs/source/reference/index.rst
Regarding #225 along with a tiny document fix.
> Add note on checkpoints and fix broken autofunction

- chainermn/communicators/_memory_utility.py
- chainermn/communicators/dummy_communicator.py
- chainermn/communicators/flat_communicator.py
- chainermn/communicators/hierarchical_communicator.py
- chainermn/communicators/naive_communicator.py
- chainermn/communicators/non_cuda_aware_communicator.py
- chainermn/communicators/pure_nccl_communicator.py
- chainermn/communicators/single_node_communicator.py
- chainermn/communicators/two_dimensional_communicator.py
- tests/chainermn_tests/communicator_tests/test_communicator.py
This PR fixed bcast_data for FP16 in PureNcclCommunicator.
> Bugfix bcast for FP16

- docs/source/installation/guide.rst
Thanks @nobu-k for pointing out #280
> Manual cherry-pick of fda23e482d37321

- chainermn/functions/batch_normalization.py
This PR is based on #276 by @okuta .
Since the PR failed in Travis CI test due to a problem in `.travis.yml` code, I created an updated PR based on #276.
> Reduce CUDA kernel launch in BN (updated)

- docs/source/tutorial/tips_faqs.rst
- examples/imagenet/train_imagenet.py
> Workaround forkserver

- chainermn/communicators/mpi_communicator_base.py
- chainermn/communicators/non_cuda_aware_communicator.py
- chainermn/communicators/single_node_communicator.py
- tests/chainermn_tests/communicator_tests/test_communicator.py
This PR addresses https://github.com/chainer/chainermn/issues/283
> bugfix bcast
